-- 상품을 구매한 회원 비율 구하기 --

SELECT YEAR(S.SALES_DATE) AS YEAR, MONTH(S.SALES_DATE) AS MONTH, COUNT(*) AS PUCHASED_USERS, -- 그룹화한 곳에서 해당 날짜에 주문한 총주문수를 구한다.
-- 서브 쿼리로 2021년에 가입한 총 회원수를 들고 온다.
ROUND(COUNT(*)/(SELECT COUNT(*) FROM USER_INFO GROUP BY YEAR(JOINED) = '2021' LIMIT 1),1) AS PUCHASED_RATIO
FROM USER_INFO I
JOIN (
SELECT USER_ID, SALES_DATE
FROM ONLINE_SALE
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), USER_ID) AS S -- ONLINE_SALE테이블에서 같은 아디로 같은 달에 시킨사람을 중복을 제거한다.
ON S.USER_ID = I.USER_ID AND LEFT(I.JOINED,4) = '2021' -- 두테이블의 ID가 같고 회원가입 날짜가 2021년만 들고온다.
GROUP BY YEAR, MONTH -- 년과 달로 그룹화
ORDER BY YEAR, MONTH